services:
  - type: web
    name: background-remover-easy
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    env: node
    envVars:
      - key: NODE_ENV
        value: production
    staticAssets:
      - path: /public